### ISSUE TITLE
Update Carla to 2.0.0 and Fluidsynth to 2.0.5

### ISSUE THREAD

**Issue by Jacalz** [flathub/io.lmms.LMMS#3]
I suggest that fluidsynth shoudl be updated to the very latest and greatest release version [2.0.5](https://github.com/FluidSynth/fluidsynth/archive/v2.0.5.tar.gz). The version includes a lot of bug-fixes, improvements and a couple optimizations over the current versions.

Carla would also be of interest to update as it saw the update to version [2.0.0](https://github.com/falkTX/Carla/releases/tag/v2.0.0) and that too brought a lot of good changes and improvements along the board.

**Comment by hfiguiere** [comment]
This should be in the next flathub build.
