### ISSUE TITLE
Some CAPS plugins are missing

### ISSUE THREAD

**Issue by Bleuzen** [flathub/io.lmms.LMMS#30]
Hi, so I switched to the flathub version of LMMS and can't open my old projects anymore. It always fails at loading some plugins (mainly from caps):
![grafik](https://user-images.githubusercontent.com/12885163/141689183-48b5fc0c-fd3e-49be-99f1-168365d7ba56.png)

So I opened a new project and compared the available plugins from the LMMS appimage vs the flatpak.
Here are the search results when searching for caps plugins...

appimage:
![grafik](https://user-images.githubusercontent.com/12885163/141689207-45a34faa-94d3-46df-9345-dfd2f5ea3723.png)

flatpak:
![grafik](https://user-images.githubusercontent.com/12885163/141689212-d608074e-00f7-4403-9497-39d477743ee6.png)

The search term is the same, but the results are different. There are different plugins available. In the flatpak version, some have another name or are missing completely.

As an example here the Plate plugin which I used in one of my projects and is also in the error message in the first screenshot.

In the appimage it is called "C* Plate2x2":
![grafik](https://user-images.githubusercontent.com/12885163/141689293-84573358-cfae-4995-91d2-1f815e8a3868.png)

But in flatpak "C* PlateX2":
![grafik](https://user-images.githubusercontent.com/12885163/141689325-75430a4d-c38e-435a-beea-59003f38127a.png)

From what I can see, the plugins seem to be the same, but the name is different, so it fails loading my projects.

Also for example the Clip plugin is missing completely.

appimage:
![grafik](https://user-images.githubusercontent.com/12885163/141689392-bc0cddb7-fcd5-451c-b9f0-52f9ec9bd936.png)

flatpak:
![grafik](https://user-images.githubusercontent.com/12885163/141689398-517937d1-dec4-4362-8bea-ae6fe1f9d461.png)

I have installed the "org.freedesktop.LinuxAudio.Plugins.CAPS//21.08" plugins, but this seems not enough.
Maybe it has something to do with this build option?:
https://github.com/flathub/io.lmms.LMMS/blob/379b11d0b123ebed84b689e1602927545efccef3/io.lmms.LMMS.json#L217

**Comment by hfiguiere** [comment]
closed with #32
