### ISSUE TITLE
wrapper script won't run from desktop

### ISSUE THREAD

**Issue by Bleuzen** [flathub/io.lmms.LMMS#35]
Hi, I currently face this problem with Carla and haven't tested with LMMS yet, but I'm pretty sure it will hold true here too.

While you set the command to be `lmms-wrap` here:
https://github.com/flathub/io.lmms.LMMS/blob/c15134ed81dc0296b37b9da155fc2f0cbe4e4472/io.lmms.LMMS.json#L6

it works when running LMMS via command:
`flatpak run io.lmms.LMMS`

but most users will start it from the desktop app menu and in this case, the command from the exported desktop file will be executed, which looks like this:
![grafik](https://user-images.githubusercontent.com/12885163/144748755-ae884626-4982-456c-a392-e4fa3467c08d.png)

Now when you run LMMS / Carla from desktop, it will directly run the `lmms` command and not the wrapper script, causing the env vars to not get set.

Guess we will have to edit the desktop files too to get flatpak to pick the right start command.

**Comment by Bleuzen** [comment]
@hfiguiere  maybe this should be discussed to change in flatpak? Why can we set a "command" property if it will get ignored and use the default command for the desktop file anyway? not sure if this is a flatpak bug or intended to be like this.

**Comment by hfiguiere** [comment]
I had some fixes I forgot to push. :-(

**Comment by hfiguiere** [comment]
new build should be available in a bit.
