### ISSUE TITLE
Unable to drag and drop instruments

### ISSUE THREAD

**Issue by RocketRide9** [flathub/io.lmms.LMMS#44]
I'm unable to drag and drop instruments from the sidebar to the Song-Editor or within the Beat+Bassline Editor. 
```
 ~ LANG='C' flatpak info io.lmms.LMMS

LMMS - A music production application

          ID: io.lmms.LMMS
         Ref: app/io.lmms.LMMS/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.2.2
     License: GPL-2.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 115.4?MB
     Runtime: org.kde.Platform/x86_64/5.15-21.08
         Sdk: org.kde.Sdk/x86_64/5.15-21.08

      Commit: a05f380bc012bb537c966ab01ae45cff9a8ccf045bbcc85c89d65eb2048ac03e
      Parent: 8144c0cb57aaa964f5825c5ff4dccdc35aefdbdc1e8140c071804340cdcd872c
     Subject: Downgrade runtime (baff50f3)
        Date: 2022-12-19 21:57:42 +0000
```
Note: i had to downgrade the runtime to avoid #43 :
`sudo flatpak update --commit=a6e1676859d826a5a2d64cefce1feabb32fde8fe97f73360ba75c262051f510b org.kde.Platform//5.15-21.08`

**Comment by pastthepixels** [comment]
This seems to be more of a problem with GNOME 44 and Qt. There was an issue (https://gitlab.gnome.org/GNOME/mutter/-/issues/2715) for it but it seems to be closed now with a patch on its way. Dragging and dropping with Fedora 38 still doesn't work right now but it should be updated soon.

**Comment by RocketRide9** [comment]
fedora updated their mutter package. issue is gone
