### ISSUE TITLE
flathubbot : FAILURE

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/io.lmms.LMMS#5]
https://flathub.org/builds/#/builders/12/builds/609
```
builddir/files/share/appdata/io.lmms.LMMS.appdata.xml: FAILED:
• tag-missing           : <description> required
Validation of files failed
```

**Comment by hfiguiere** [comment]
yeah and I have no idea why this is happening. The file validate locally, in didn't even change since last build.

**Comment by hfiguiere** [comment]
This was fixed too. Current build should be out now.

**Comment by hfiguiere** [comment]
publish is failing...

**Comment by hfiguiere** [comment]
build has been published
