### ISSUE TITLE
Unable to drag and drop instruments

### ISSUE THREAD

**Issue by stove-panini** [flathub/io.lmms.LMMS#7]
I'm unable to drag and drop instruments from the sidebar to the Song-Editor or within the Beat+Bassline Editor. I'm on Fedora 31, running the default GNOME desktop, and using the latest Flatpak version at the time of submitting this issue:
```
$ flatpak info io.lmms.LMMS 

LMMS - A music production application

          ID: io.lmms.LMMS
         Ref: app/io.lmms.LMMS/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.2.1
     License: GPL-2.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 151.2 MB
     Runtime: org.kde.Platform/x86_64/5.13
         Sdk: org.kde.Sdk/x86_64/5.13

      Commit: 4a70e8f72c51811ee209c6868405ddcc57eb08ec6f6bba06189ad90397989163
      Parent: 3283c0e1a8f5adac11d8532f0658a329c435a540a29dfeeeffb6f5b9c12cff30
     Subject: Update to fluidsynth 2.0.8 (0ed0436b)
        Date: 2019-10-27 20:06:14 +0000
```
Please let me know if I can provide any more info.

**Comment by hfiguiere** [comment]
If I run with `flatpak-builder --run` it does work, Indeed if I run the flatpak from flathub it doesn't.

**Comment by hfiguiere** [comment]
This should be fixed in the next flathub build.

Sorry it took so long to fix.

**Comment by stove-panini** [comment]
Big thanks
